language: node_js
node_js:
  - "node"

cache:
  directories:
    - "node_modules"
  
before_script:
  - npm install -g purescript
  - npm install -g pulp bower
  - bower install

script:
  - pulp build
  - pulp browserify --to static/Main.js

  
